//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int id_curso { get; set; }
        public string codigo_curso { get; set; }
        public string nombre_curso { get; set; }
        public string horario { get; set; }
        public string profesor { get; set; }
        public int estado_curso { get; set; }
        public string facultad { get; set; }
    }
}
